### ISSUE TITLE
Melhorar coesão

### ISSUE THREAD

**Issue by EpicEric** [EpicEric/tcc#1]
O texto atualmente não tem um fio narrativo, e as partes estão desconexas.

Devemos tomar uma abordagem mais narrativa, e conectar cada parte do texto com a anterior.

Sugestão:

* Na introdução, apresentar o problema original e as necessidades. A partir disso, desenvolver a ideia de um MVP, as tecnologias necessárias para tal MVP, e como será realizada essa ideia, pelos estudos e desenvolvimento.

* Em aspectos conceituais, aprofundar-se no que foi apresentado na seção anterior com relação à base teórica das tecnologias por trás do caso de uso principal. Em tecnologias utilizadas, falar das ferramentas que serão o framework para as tecnologias.

* Em metodologia de trabalho, aprofundar-se na parte da introdução sobre como se dará o desenvolvimento. Relacionar com a implementação das tecnologias utilizadas.

* Em especificação de requisitos, objetivar as necessidades das tecnologias utilizadas. Detalhar os casos de uso a partir da introdução, e expressar como os aspectos conceituais serão utilizados aqui.

* Em implementação, relacionar à metodologia para a tomada de decisões e à especificação de requisitos para a verificação. Falar de dificuldades explicitando diretamente as tecnologias utilizadas.

**Comment by mateusnakajo** [comment]
Concordo com as sugestões. Alguns pontos que podem ser adicionados a estes que você apresentou:

- Em aspectos conceituais, apresentar os algoritmos considerados para o caso de uso principal.
- Em especificação de requisitos, colocar somente os casos de uso que serão implementados. Colocar os demais em Perspectiva de continuidade e explicar quais as tecnologias necessárias para a implementação deles.
- Em implementação, explicar porque determinado algoritmo foi selecionado para a versão final, e compará-lo com os outros.
- Em Perspectiva de continuidade, apresentar outros parâmetros que podem ser considerados para melhorar o algoritmo.
